<a href="https://colab.research.google.com/github/hemanagasai/narra_IT533/blob/main/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
amazon =pd.read_csv("https://raw.githubusercontent.com/hemanagasai/narra_IT533/main/amazon_toy_sample_clean.csv",encoding="ISO-8859-1")
amazon.dropna(inplace=True)

In [4]:
a = amazon
a.head()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,status,number_of_reviews,number_of_answered_questions,average_review_rating_of_5,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews
0,dafc6b4ba4b4a3e7b4ff83402a196ae8,Dinosaur Eggs,Halsall,0.29,3,new,3,2,4.0,Figures & Playsets > Dinosaurs,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,Manufacturer's Description not available,Technical Details Item Weight82 g Product Dime...,Not available,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,None,Fascinating fun // 4.0 // 25 Nov. 2008 // By\n...
1,ba85fb9368114fce646379ed12750a5f,Neopets 4 Trading Card Fun Packs (2 Bonus Cards),Neopets,0.38,2,new,2,1,4.5,Hobbies > Trading Cards & Accessories > Packs ...,Unknown,Manufacturer's Description not available,Technical Details Item Weight454 g Product Dim...,Not available,Not available,None,Never Too Old // 4.0 // 6 Nov. 2013 // By\n ...
2,14e24c29ba38c2717754baa2638f242a,"Latex Assorted Water Balloons, Pack of 40",Unique Party,0.39,7,new,2,1,4.5,Party Supplies > Decorations > Balloons,http://www.amazon.co.uk/Latex-Cannonball | htt...,Colour Name:Assorted Bold | Size Name:Pack o...,Technical Details Item Weight222 g Product Dim...,Colour Name:Assorted Bold | Size Name:Pack o...,http://www.amazon.co.uk/Water-Bombs-Pack-100-A...,None,Great item // 4.0 // 27 Dec. 2015 // By\n \...
4,7b72f597db5d74d35c4f91ef69708cf1,4 Packs of Mini Colouring Pencils (4 pencils i...,unisex party bag fillers,0.60,7,new,21,1,4.3,Arts & Crafts > Colouring Pencils,http://www.amazon.co.uk/12-Mini-Christmas-Colo...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,Technical Details Item Weight59 g Product Dime...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,http://www.amazon.co.uk/20-Packs-Wax-Crayons-P...,How many packs in the box. // I got four Mimi ...,Well made and presented // 4.0 // 6 April 2015...
5,7b8a04095b5e4984c57fd45eb327feb1,100 Deep Red Rose Silk Petals Confetti - Weddi...,Shatchi,0.64,6,new,10,2,4.1,"Party Supplies > Banners, Stickers & Confetti ...",http://www.amazon.co.uk/Valentines | http://ww...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,Technical Details Manufacturer recommended age...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,http://www.amazon.co.uk/300-Deep-Silk-Rose-Pet...,None,Five Stars // 5.0 // 2 Dec. 2015 // By\n \n...

1. Data Transformation: Pick three variables whose data types may be more useful as another
data type and utransform them to numeric or character/ categorical format. Then, insert a
text section into your notebook and explain in no less than 3 sentences what this
transformation will allow you to accomplish analytically later on

In [5]:
# First Variable: status
# First, we back the dataframe up.
a1=amazon
# Now we build the column and copy the original values into it
a1['status_num'] = a1.status
# Third, we convert state_num into categorical
a1['status_num']= a1['status_num'].astype('category')
# Then, we replace the strings with the category indices
a1['status_num']= a1['status_num'].cat.codes
# Now, we check the data types
a1.dtypes[['status','status_num']]

status        object
status_num      int8
dtype: object

In [6]:
a1.head()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,status,number_of_reviews,number_of_answered_questions,average_review_rating_of_5,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,status_num
0,dafc6b4ba4b4a3e7b4ff83402a196ae8,Dinosaur Eggs,Halsall,0.29,3,new,3,2,4.0,Figures & Playsets > Dinosaurs,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,Manufacturer's Description not available,Technical Details Item Weight82 g Product Dime...,Not available,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,None,Fascinating fun // 4.0 // 25 Nov. 2008 // By\n...,1
1,ba85fb9368114fce646379ed12750a5f,Neopets 4 Trading Card Fun Packs (2 Bonus Cards),Neopets,0.38,2,new,2,1,4.5,Hobbies > Trading Cards & Accessories > Packs ...,Unknown,Manufacturer's Description not available,Technical Details Item Weight454 g Product Dim...,Not available,Not available,None,Never Too Old // 4.0 // 6 Nov. 2013 // By\n ...,1
2,14e24c29ba38c2717754baa2638f242a,"Latex Assorted Water Balloons, Pack of 40",Unique Party,0.39,7,new,2,1,4.5,Party Supplies > Decorations > Balloons,http://www.amazon.co.uk/Latex-Cannonball | htt...,Colour Name:Assorted Bold | Size Name:Pack o...,Technical Details Item Weight222 g Product Dim...,Colour Name:Assorted Bold | Size Name:Pack o...,http://www.amazon.co.uk/Water-Bombs-Pack-100-A...,None,Great item // 4.0 // 27 Dec. 2015 // By\n \...,1
4,7b72f597db5d74d35c4f91ef69708cf1,4 Packs of Mini Colouring Pencils (4 pencils i...,unisex party bag fillers,0.60,7,new,21,1,4.3,Arts & Crafts > Colouring Pencils,http://www.amazon.co.uk/12-Mini-Christmas-Colo...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,Technical Details Item Weight59 g Product Dime...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,http://www.amazon.co.uk/20-Packs-Wax-Crayons-P...,How many packs in the box. // I got four Mimi ...,Well made and presented // 4.0 // 6 April 2015...,1
5,7b8a04095b5e4984c57fd45eb327feb1,100 Deep Red Rose Silk Petals Confetti - Weddi...,Shatchi,0.64,6,new,10,2,4.1,"Party Supplies > Banners, Stickers & Confetti ...",http://www.amazon.co.uk/Valentines | http://ww...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,Technical Details Manufacturer recommended age...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,http://www.amazon.co.uk/300-Deep-Silk-Rose-Pet...,None,Five Stars // 5.0 // 2 Dec. 2015 // By\n \n...,1

In [7]:
# Second Variable: manufacturer
# First, we back the dataframe up.
a1=amazon
# Now we build the column and copy the original values into it
a1['manufacturer_num'] = a1.manufacturer
# Third, we convert state_num into categorical
a1['manufacturer_num']= a1['manufacturer_num'].astype('category')
# Then, we replace the strings with the category indices
a1['manufacturer_num']= a1['manufacturer_num'].cat.codes
# Now, we check the data types
a1.dtypes[['manufacturer','manufacturer_num']]

manufacturer        object
manufacturer_num     int16
dtype: object

In [8]:
a1.head()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,status,number_of_reviews,number_of_answered_questions,average_review_rating_of_5,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,status_num,manufacturer_num
0,dafc6b4ba4b4a3e7b4ff83402a196ae8,Dinosaur Eggs,Halsall,0.29,3,new,3,2,4.0,Figures & Playsets > Dinosaurs,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,Manufacturer's Description not available,Technical Details Item Weight82 g Product Dime...,Not available,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,None,Fascinating fun // 4.0 // 25 Nov. 2008 // By\n...,1,632
1,ba85fb9368114fce646379ed12750a5f,Neopets 4 Trading Card Fun Packs (2 Bonus Cards),Neopets,0.38,2,new,2,1,4.5,Hobbies > Trading Cards & Accessories > Packs ...,Unknown,Manufacturer's Description not available,Technical Details Item Weight454 g Product Dim...,Not available,Not available,None,Never Too Old // 4.0 // 6 Nov. 2013 // By\n ...,1,1025
2,14e24c29ba38c2717754baa2638f242a,"Latex Assorted Water Balloons, Pack of 40",Unique Party,0.39,7,new,2,1,4.5,Party Supplies > Decorations > Balloons,http://www.amazon.co.uk/Latex-Cannonball | htt...,Colour Name:Assorted Bold | Size Name:Pack o...,Technical Details Item Weight222 g Product Dim...,Colour Name:Assorted Bold | Size Name:Pack o...,http://www.amazon.co.uk/Water-Bombs-Pack-100-A...,None,Great item // 4.0 // 27 Dec. 2015 // By\n \...,1,1585
4,7b72f597db5d74d35c4f91ef69708cf1,4 Packs of Mini Colouring Pencils (4 pencils i...,unisex party bag fillers,0.60,7,new,21,1,4.3,Arts & Crafts > Colouring Pencils,http://www.amazon.co.uk/12-Mini-Christmas-Colo...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,Technical Details Item Weight59 g Product Dime...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,http://www.amazon.co.uk/20-Packs-Wax-Crayons-P...,How many packs in the box. // I got four Mimi ...,Well made and presented // 4.0 // 6 April 2015...,1,1753
5,7b8a04095b5e4984c57fd45eb327feb1,100 Deep Red Rose Silk Petals Confetti - Weddi...,Shatchi,0.64,6,new,10,2,4.1,"Party Supplies > Banners, Stickers & Confetti ...",http://www.amazon.co.uk/Valentines | http://ww...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,Technical Details Manufacturer recommended age...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,http://www.amazon.co.uk/300-Deep-Silk-Rose-Pet...,None,Five Stars // 5.0 // 2 Dec. 2015 // By\n \n...,1,1312

In [10]:
# Third Variable: average_review_rating_of_5
# First, we back the dataframe up.
a1=amazon
# Now we build the column and copy the original values into it
a1['average_review_rating_of_5_int'] = a1.average_review_rating_of_5
# Third, we convert pledged_num into int32
a1['average_review_rating_of_5_int']= a1['average_review_rating_of_5_int'].astype('int32')
# Now, we check the data types
a1.dtypes[['average_review_rating_of_5','average_review_rating_of_5_int']]

average_review_rating_of_5        float64
average_review_rating_of_5_int      int32
dtype: object

In [11]:
a1.head()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,status,number_of_reviews,number_of_answered_questions,average_review_rating_of_5,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,status_num,manufacturer_num,average_review_rating_of_5_int
0,dafc6b4ba4b4a3e7b4ff83402a196ae8,Dinosaur Eggs,Halsall,0.29,3,new,3,2,4.0,Figures & Playsets > Dinosaurs,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,Manufacturer's Description not available,Technical Details Item Weight82 g Product Dime...,Not available,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,None,Fascinating fun // 4.0 // 25 Nov. 2008 // By\n...,1,632,4
1,ba85fb9368114fce646379ed12750a5f,Neopets 4 Trading Card Fun Packs (2 Bonus Cards),Neopets,0.38,2,new,2,1,4.5,Hobbies > Trading Cards & Accessories > Packs ...,Unknown,Manufacturer's Description not available,Technical Details Item Weight454 g Product Dim...,Not available,Not available,None,Never Too Old // 4.0 // 6 Nov. 2013 // By\n ...,1,1025,4
2,14e24c29ba38c2717754baa2638f242a,"Latex Assorted Water Balloons, Pack of 40",Unique Party,0.39,7,new,2,1,4.5,Party Supplies > Decorations > Balloons,http://www.amazon.co.uk/Latex-Cannonball | htt...,Colour Name:Assorted Bold | Size Name:Pack o...,Technical Details Item Weight222 g Product Dim...,Colour Name:Assorted Bold | Size Name:Pack o...,http://www.amazon.co.uk/Water-Bombs-Pack-100-A...,None,Great item // 4.0 // 27 Dec. 2015 // By\n \...,1,1585,4
4,7b72f597db5d74d35c4f91ef69708cf1,4 Packs of Mini Colouring Pencils (4 pencils i...,unisex party bag fillers,0.60,7,new,21,1,4.3,Arts & Crafts > Colouring Pencils,http://www.amazon.co.uk/12-Mini-Christmas-Colo...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,Technical Details Item Weight59 g Product Dime...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,http://www.amazon.co.uk/20-Packs-Wax-Crayons-P...,How many packs in the box. // I got four Mimi ...,Well made and presented // 4.0 // 6 April 2015...,1,1753,4
5,7b8a04095b5e4984c57fd45eb327feb1,100 Deep Red Rose Silk Petals Confetti - Weddi...,Shatchi,0.64,6,new,10,2,4.1,"Party Supplies > Banners, Stickers & Confetti ...",http://www.amazon.co.uk/Valentines | http://ww...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,Technical Details Manufacturer recommended age...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,http://www.amazon.co.uk/300-Deep-Silk-Rose-Pet...,None,Five Stars // 5.0 // 2 Dec. 2015 // By\n \n...,1,1312,4

Here Data transformation is done on status, manufacturer, average_review_rating_of_5.

status data transformation to categorical makes us to make categories in status values.

manufacturer data transformation to categorical makes us to make categories in manufacturer values.

average_review_rating_of_5 transformation to integer makes us to know how many reviews comes under review.

2. Data Substitution: Substitute values in at least two variables. Insert a text section into your
notebook and explain in no less than 3 sentences how you decided what values to use for
substitution and, in addition to your explanation, show your code.

In [12]:
a2 = amazon
a2.customer_questions_and_answers.unique()
# Instead of building another column to see any transformations, we will substitute
# For this purpose, we're using the replace() method from pandas
a2.customer_questions_and_answers.replace('None','0', inplace=True)
# Did we indeed replace all '?'? Let's check:
a2[a2['customer_questions_and_answers'] == 'None']

Empty DataFrame
Columns: [uniq_id, product_name, manufacturer, price, number_available_in_stock, status, number_of_reviews, number_of_answered_questions, average_review_rating_of_5, amazon_category_and_sub_category, customers_who_bought_this_item_also_bought, description, product_information, product_description, items_customers_buy_after_viewing_this_item, customer_questions_and_answers, customer_reviews, status_num, manufacturer_num, average_review_rating_of_5_int]
Index: []

In [ ]:
a2.head()

In [15]:
a2.description.unique()
# Instead of building another column to see any transformations, we will substitute
# For this purpose, we're using the replace() method from pandas
a2.description.replace('Manufacturer\'s Description not available','Not Available',inplace=True)
# Did we indeed replace all '?'? Let's check:
a2[a2['description'] == 'Manufacturer\'s Description not available']

Empty DataFrame
Columns: [uniq_id, product_name, manufacturer, price, number_available_in_stock, status, number_of_reviews, number_of_answered_questions, average_review_rating_of_5, amazon_category_and_sub_category, customers_who_bought_this_item_also_bought, description, product_information, product_description, items_customers_buy_after_viewing_this_item, customer_questions_and_answers, customer_reviews, status_num, manufacturer_num, average_review_rating_of_5_int]
Index: []

In [ ]:
a2.head()

Data substitution is done on customer_questions_and_answers and description.

In description variable replacing Manufacturer's Description not available to Not available to be precise.

In customer_questions_and_answers variable replacing None as 0 to be understand clearly.

Question 3: Data Reduction: Pick two variables that could be simplified by binning or bucketing,
or by normalization or standardization. Then perform the operation(s) you have chosen. Insert a
text section into your notebook and explain in no less than 3 sentences what benefit this may
provide for any later analysis.

In [17]:
a1.average_review_rating_of_5.describe()

count    6312.000000
mean        4.686565
std         0.427846
min         0.000000
25%         4.500000
50%         4.900000
75%         5.000000
max         5.000000
Name: average_review_rating_of_5, dtype: float64

In [21]:
# Variable 2: usd_goal_real simplified by using Bucketing method.
# Setting up our 5 buckets and their labels
buckets = [ 0, 1, 2, 3, 4, 5]
bucketlabels = ['very bad','bad', 'Average', 'Good', 'Very Good']
# Using cut() to separate data into the buckets we have built
a1['buckets'] = pd.cut(a1['average_review_rating_of_5'] , bins=buckets, labels=bucketlabels, include_lowest=True)
# Check if we have the new attribute 'buckets' at the end of our dataset
a1.head()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,status,number_of_reviews,number_of_answered_questions,average_review_rating_of_5,amazon_category_and_sub_category,...,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,status_num,manufacturer_num,average_review_rating_of_5_int,buckets
0,dafc6b4ba4b4a3e7b4ff83402a196ae8,Dinosaur Eggs,Halsall,0.29,3,new,3,2,4.0,Figures & Playsets > Dinosaurs,...,Not Available,Technical Details Item Weight82 g Product Dime...,Not available,http://www.amazon.co.uk/Hatch-em-TY63-Hatching...,0,Fascinating fun // 4.0 // 25 Nov. 2008 // By\n...,1,632,4,Good
1,ba85fb9368114fce646379ed12750a5f,Neopets 4 Trading Card Fun Packs (2 Bonus Cards),Neopets,0.38,2,new,2,1,4.5,Hobbies > Trading Cards & Accessories > Packs ...,...,Not Available,Technical Details Item Weight454 g Product Dim...,Not available,Not available,0,Never Too Old // 4.0 // 6 Nov. 2013 // By\n ...,1,1025,4,Very Good
2,14e24c29ba38c2717754baa2638f242a,"Latex Assorted Water Balloons, Pack of 40",Unique Party,0.39,7,new,2,1,4.5,Party Supplies > Decorations > Balloons,...,Colour Name:Assorted Bold | Size Name:Pack o...,Technical Details Item Weight222 g Product Dim...,Colour Name:Assorted Bold | Size Name:Pack o...,http://www.amazon.co.uk/Water-Bombs-Pack-100-A...,0,Great item // 4.0 // 27 Dec. 2015 // By\n \...,1,1585,4,Very Good
4,7b72f597db5d74d35c4f91ef69708cf1,4 Packs of Mini Colouring Pencils (4 pencils i...,unisex party bag fillers,0.60,7,new,21,1,4.3,Arts & Crafts > Colouring Pencils,...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,Technical Details Item Weight59 g Product Dime...,4 x Mini Colouring Pencils - Pack of 4 Size: 8...,http://www.amazon.co.uk/20-Packs-Wax-Crayons-P...,How many packs in the box. // I got four Mimi ...,Well made and presented // 4.0 // 6 April 2015...,1,1753,4,Very Good
5,7b8a04095b5e4984c57fd45eb327feb1,100 Deep Red Rose Silk Petals Confetti - Weddi...,Shatchi,0.64,6,new,10,2,4.1,"Party Supplies > Banners, Stickers & Confetti ...",...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,Technical Details Manufacturer recommended age...,Pack of 100 Deep Red Silk Rose Petals Luxury s...,http://www.amazon.co.uk/300-Deep-Silk-Rose-Pet...,0,Five Stars // 5.0 // 2 Dec. 2015 // By\n \n...,1,1312,4,Very Good

In [23]:
a1.groupby(['buckets']).count()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,status,number_of_reviews,number_of_answered_questions,average_review_rating_of_5,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,status_num,manufacturer_num,average_review_rating_of_5_int
buckets,,,,,,,,,,,,,,,,,,,,
very bad,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
bad,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Average,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Good,787,787,787,787,787,787,787,787,787,787,787,787,787,787,787,787,787,787,787,787
Very Good,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509,5509

In [25]:
a1.number_of_reviews.describe()
bins = np.linspace(a1.number_of_reviews.min(),a1.number_of_reviews.max(),5)
bins
labels = ['very_Few', 'Few','more','many']
# Variable 1: backers simplified by using Binning methods.
a3 = amazon 
a3['bins'] = pd.cut(a3['number_of_reviews'], bins=bins, labels=labels, include_lowest=True)
a3.head()
a3.groupby(['bins']).count()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,status,number_of_reviews,number_of_answered_questions,average_review_rating_of_5,amazon_category_and_sub_category,...,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,status_num,manufacturer_num,average_review_rating_of_5_int,buckets
bins,,,,,,,,,,,,,,,,,,,,,
very_Few,6299,6299,6299,6299,6299,6299,6299,6299,6299,6299,...,6299,6299,6299,6299,6299,6299,6299,6299,6299,6299
Few,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
more,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
many,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

Data Reduction done on number_of_reviews and average_review_rating_of_5 using bucketing and binning methods.

number_of_reviews is reduced using binning because to categorize all products based on number of reviews.

average_review_rating_of_5 is reduced using bucketing to categorize all products depends on rating.

*4. Now that you have a better dataset, think about any important organizational analytical
questions that management could ask about the dataset in order to help them make business or
organizational decisions. 

*What can we analysis with the average rating of 5?